# Generated by Django 3.2.4 on 2021-06-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210619_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'education_teacher'},
        ),
    ]
