# Generated by Django 3.2.4 on 2021-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210619_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('salary', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('F', 'Full time'), ('P', 'Part Time')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.baseemployee',),
        ),
    ]
