# Generated by Django 3.2.4 on 2021-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_baseemployee_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
