# Generated by Django 3.2.4 on 2021-06-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='user',
        ),
    ]
